###Customer Sign up endpoint

POST http://localhost:3001/v1/customer
Content-Type: application/json

{
     "name": "Menuka Ram",
    "email": "menuka@gmail.com",
    "password": "Manakamana123",
    "phone": "04212121212",
    "isCustomer": "false",
    "isAdmin": "true"
}

###Customer Sign In endpoint
POST http://localhost:3001/v1/customer/login
Content-Type: application/json

{
         "email": "dfdd@gmail.com",
    "password": "Manakamana123"
}

###Get a Customer profile endpoint
GET http://localhost:3001/v1/customer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRmZGRAZ21haWwuY29tIiwiX2lkIjoiNjIyNTRhNDk0ZmY3YWFhMmQ4ZWQ2YmFkIiwiaWF0IjoxNjU3ODQ1Nzk2LCJleHAiOjE2NTc4NDY2OTZ9.lUMmacHth8WWlZ72zCyLjKMorcNETYfLGqSu_L79QxE

### Token routers

### Get refreshed tokens from
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRmZGRAZ21haWwuY29tIiwiaWF0IjoxNjMzNjU2MDQ1LCJleHAiOjE2MzUzODQwNDV9.QUpsfOlbYhsbahptbMnVKrYSNoQIXyxqP5-UHUWZXTQ

      
###Password reset endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "Sadhguru@gmail.com"
}

###User Logout Endpoint   
DELETE http://localhost:3001/v1/customer/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRmZGRAZ21haWwuY29tIiwiX2lkIjoiNjE1ZmQ3MTZmOTVjNDFmMGYxNDkyNzVmIiwiaWF0IjoxNjMzNjgxNDE0LCJleHAiOjE2MzM2ODIzMTR9.BjsnOSuTOStnDObfOzTI4OqSpPAEHWDdCCaFyxFWGYI
